package com.example.demo.jdbc;

import org.springframework.stereotype.Service;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

@Service
public class DBSchemeManager
{

    public void initDataBase(Connection connection)
    {
        dropTables(connection);
        createTables(connection);
    }

    private void createTables(Connection connection)
    {
        String dogTableSQL = "CREATE TABLE DOG (" +
                "ID LONG generated by default as identity (start with 1), " +
                "NAME VARCHAR(50), " +
                "AGE INTEGER" +
                ");";

        String addressTableSQL = "CREATE TABLE ADDRESS (" +
                "ID LONG generated by default as identity (start with 1), " +
                "COUNTRY VARCHAR(50), " +
                "CITY VARCHAR(50), " +
                "HOUSE INTEGER, " +
                "FK_DOG LONG" +
                ");";

        execute(dogTableSQL, connection);
        execute(addressTableSQL, connection);
    }

    private void dropTables(Connection connection)
    {
        execute("DROP TABLE IF EXISTS ADDRESS;", connection);
        execute("DROP TABLE IF EXISTS DOG;", connection);
    }

    private void execute(String sql, Connection connection)
    {
        try
        {
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();
            statement.close();
        }
        catch (SQLException e)
        {
            throw new RuntimeException(e);
        }
    }

}
